### ISSUE TITLE
I don't understand how VOLUME instruction in Dockerfile is useful at all

### ISSUE THREAD

**Issue by vvkleban** [crashvb/mysql-docker#1]
I see that mysql guys have it in their Dockerfile themselves. However I don't see how using it is beneficial at all. docker run creates a volume with some random name. It gives no straightforward possibility of reusing an existing volume - the entire point behind docker volumes. It doesn't even reuse already created volume, when I delete and recreate the container.

Am I not understanding entire logic behind it, or would it have been more appropriate to separate container creation and volume creation (or adoption) for the user to have an option for the DB volume? This, of course, would require a bit better logic in your entrypoint scripts to detect whether there is already existing DB in the volume to proceed accordingly.

**Comment by crashvb** [comment]
A volume was declared to isolate the (potentially) persistent data from the container filesystem. There is a [branch point](https://github.com/crashvb/mysql-docker/blob/3ce057ed89879443775180308db79ebe8607be3e/entrypoint.mysql#L17) that should restrict database initialization to scenarios where the volume is empty.
